---
parent: 'test_cases/test_branch_jenkins_openshift_login_plugin.yml'
overrides:
  sync_repos:
    - name: "jenkins-openshift-login-plugin"
      type: "pull_request"
  test: "jenkins-openshift-login-plugin"