---
parent: 'common/test_cases/origin.yml'
extensions:
  actions:
    - type: "script"
      title: "run unit tests"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/scripts hack/env TEST_KUBE='true' JUNIT_REPORT='true' make test-unit -k