---
parent: 'common/test_cases/origin_installed_release.yml'
extensions:
  sync_repos:
    - name: "jenkins-sync-plugin"
  actions:
    - type: "script"
      title: "build the jenkins sync plugin and test image"
      repository: "jenkins-sync-plugin"
      script: |-
        export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
        mvn package
        cd PR-Testing
        ./build-jenkins-sync-plugin-snapshot-image.sh
    - type: "script"
      title: "test the jenkins sync plugin test image against origin"
      repository: "origin"
      script: |-
        KUBECONFIG=/etc/origin/master/admin.kubeconfig USE_SNAPSHOT_JENKINS_SYNC_IMAGE=1 TEST_ONLY=true JUNIT_REPORT='true' make test-extended SUITE=core FOCUS="openshift pipeline build"