---
parent: 'common/test_cases/origin_release.yml'
overrides:
  timer: 'H H * * *'
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      timeout: 5000
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/extended.test hack/env make build-extended-test
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-extended SUITE=networking