---
- name: install tito and builddeps
  yum: name={{ item }} state=present
  with_items:
    - tito
    - createrepo_c

- name: ensure builddeps are installed
  command: chdir={{ openshift_repo_path }} yum-builddep origin.spec -y

- name: build packages
  command: chdir={{ openshift_repo_path }} tito build --test --rpm --output={{ web_docroot }}/{{ project }}
  register: pkgs_built

- name: generate repo
  command: chdir={{ web_docroot }}/{{ project }}/{{ arch }} createrepo_c .
  when: pkgs_built|success
