- debug:
    msg: "PaaS-sig Props: {{ item.prop }} [ {{ item.value }} ]"
  with_items:
    - { prop: 'project', value: "{{ project }}" }
    - { prop: 'version', value: "{{ version }}" }

- name: Check if changes have already been applied
  shell: "git log -n1 | grep 'Fixup spec file - v{{ version }}'"
  args:
    chdir: "{{ openshift_repo_path }}"
  ignore_errors: yes
  register: git_log

- name: checkout origin version
  shell: git checkout v{{ version.split('-')[0] }}
  args:
    chdir: "{{ openshift_repo_path }}"
  when: (git_log.stdout == "" and not bleeding_edge)

- name: tag origin version
  shell: git tag -d v{{ version.split('-')[0] }}
  args:
    chdir: "{{ openshift_repo_path }}"
  when: (git_log.stdout == "" and not bleeding_edge)

- name: update git vars in origin.spec
  lineinfile:
    dest: "{{ openshift_repo_path }}/origin.spec"
    regexp: "^%global os_git_vars .*$"
    line: "%global os_git_vars OS_GIT_TREE_STATE='clean' OS_GIT_VERSION=v{{ version }} OS_GIT_COMMIT= OS_GIT_MAJOR={{ version.split('.')[0] }} OS_GIT_MINOR={{ version.split('.')[1] }}+"
    backrefs: yes
    state: present
  when: git_log.stdout == ""

- name: update git version in origin.spec
  lineinfile:
    dest: "{{ openshift_repo_path }}/origin.spec"
    regexp: "^Version:.*$"
    line: "Version:        {{ version.split('-')[0] }}"
    backrefs: yes
    state: present
  when: git_log.stdout == ""

- name: update git release in origin.spec
  lineinfile:
    dest: "{{ openshift_repo_path }}/origin.spec"
    regexp: "^Release:.*$"
    line: "Release:        {{ version.split('-')[1] }}%{dist}"
    backrefs: yes
    state: present

- name: fix excluder-docker script in origin.spec
  lineinfile:
    dest: "{{ openshift_repo_path }}/origin.spec"
    regexp: "^post docker-excluder.*$"
    line: "%posttrans docker-excluder"
    backrefs: yes
    state: present

- name: git commit changes locally
  shell: git commit -m "Fixup spec file - v{{ version }}" origin.spec
  args:
    chdir: "{{ openshift_repo_path }}"
  when: git_log.stdout == ""